module.exports = {
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  username: 'postgres',
  password: '12345',
  database: 'nest_oauth',
  // charset: 'utf8mb4',
  supportBigNumbers: true,
  bigNumberStrings: false,
  migrationsRun: false,
  synchronize: true,
  logging: process.env.APP_STAGE === 'development',
  entityPrefix: process.env.DB_ENTITY_PREFIX || '',
  entities: ['dist/**/*.entity.ts', 'node_modules/**/*.entity.ts'],
};
